Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true

  Include:
  - '**/Rakefile'

  Exclude:
  - 'db/**/*'
  - 'vendor/**/*'
  - '.internal_test_app/**/*'
  - 'lib/generators/geoblacklight/templates/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
  - 'spec/**/*'
  - 'Rakefile'
  - 'lib/generators/geoblacklight/install_generator.rb'

# TODO: Refactor large methods.
Metrics/AbcSize:
  Max: 23

Metrics/MethodLength:
  Max: 15

# TODO: Add top-level class and module documentation.
Style/Documentation:
  Enabled: false

# Overrides method in blacklight. Must use method name.
Style/PredicateName:
  Exclude:
    - 'lib/geoblacklight/view_helper_override.rb'

RSpec/FilePath:
  Enabled: false

# Rubocop bug causes view specs to fail.
#  https://github.com/nevir/rubocop-rspec/issues/47
RSpec/DescribeClass:
  Enabled: false

# geoblacklight references in solr_document_spec are
# difficult to mock because of the use of 'method_missing'.
# https://relishapp.com/rspec/rspec-mocks/docs/verifying-doubles/dynamic-classes
RSpec/AnyInstance:
  Exclude:
    - 'spec/models/concerns/geoblacklight/solr_document_spec.rb'

# Offense count: 12
# Configuration parameters: AcceptedMethod.
RSpec/NotToNot:
  Exclude:
    - 'spec/controllers/catalog_controller_spec.rb'
    - 'spec/features/download_layer_spec.rb'
    - 'spec/features/exports_spec.rb'
    - 'spec/features/home_page_spec.rb'
    - 'spec/features/layer_inspection_spec.rb'
    - 'spec/features/metadata_panel_spec.rb'
    - 'spec/features/split_view.html.erb_spec.rb'
    - 'spec/features/web_services_modal_spec.rb'
    - 'spec/lib/geoblacklight/wms_layer/feature_info_response_spec.rb'
    - 'spec/lib/geoblacklight/wms_layer_spec.rb'
    - 'spec/models/concerns/geoblacklight/solr_document_spec.rb'

Style/SignalException:
  EnforcedStyle: semantic
